---

- name: Creating promteams template email directory
  file:
     path: "{{ item }}"
     state: directory
  with_items:
         - "{{ promteams_dir }}"

- name: copy email template file to server
  copy:
     src: email_template.tmpl
     dest: "{{ promteams_dir }}"

- name: Creating promteams Container
  docker_container:
    name: promteams-data
    image: quay.io/prometheusmsteams/prometheus-msteams
    state: present
    volumes:
        - "{{ promteams_dir }}/email_template.tmpl:/etc/email_template.tmpl"
    restart_policy: always
    command: /bin/true

- name: Running prometheus teams container
  docker_container:
    name: promteams
    image: "{{ prom_team_image }}"
    state: started
    published_ports:
    - 2000:2000
    volumes_from:
    - promteams-data
    env:
        TEAMS_REQUEST_URI: alertmanager
        TEMPLATE_FILE: /etc/email_template.tmpl
        TEAMS_INCOMING_WEBHOOK_URL: "{{ address_teams }}"
    restart_policy: always

- wait_for:
       port: 2000
       delay: 5

- name: restart container
  shell: docker restart promteams

- name: add prometheus config
  template:
    src: prometheus.base.yml.j2
    dest: "{{ docker_data }}/prometheus_conf/_data/prometheus.base.yml"

- name: copy file setup to rules folder in pmm-server
  copy:
    src: ./rules/
    dest: "{{ docker_data }}/prometheus_rule/_data/"

- name: restart container
  shell: docker restart pmm-server
