---

- name: Install docker.io
  apt:
    name: docker.io
    state: present

- name: install python
  apt:
    name: python3-pip
    state: present

# - name: Make sure psycopg2 is installed
#   pip:
#     name: docker
#     state: latest

- name: Install Docker Python SDK for PostgreSQL management
  pip:
    name: docker
    state: latest
    extra_args: --break-system-packages
  
