---

- hosts: test1
  become: yes
  gather_facts: yes
  # roles:

  #    - name: harderning_ubuntu_20.04
  #      when: 
  #        - iscluster == 'no'    

  #    - name: psql12_single
  #      when: 
  #        - iscluster == 'no'
  tasks:
    - name: Install postgresql as default (offline)
      shell: |
        cd /opt/psql_{{ psql_version }}
        DEBIAN_FRONTEND=noninteractive apt install --allow-downgrades -y ./*.deb
        systemctl daemon-reload
      retries: 5
      delay: 10
      register: result
      until: result.rc == 0
# - hosts: nodes
#   become: yes
#   gather_facts: yes
#   roles:

#      - name: harderning_ubuntu_20.04
#        when: 
#          - iscluster == 'yes'

#      - name: psql12_cluster
#        when: 
#          - iscluster == 'yes'

- hosts: all
  become: yes
  gather_facts: no
  roles:

     - name: barman_backup
       when: 
         - isbackup == 'yes'
         - inventory_hostname in groups['backup']
       tags:
         - backup
